[package]
name = "gksay"
version = "0.1.1"
description = "Portable text queue sender"
authors = ["GkSay"]
edition = "2021"

[lib]
name = "gksay_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
arboard = "3.6"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-global-shortcut = "2.3.2"
tokio = { version = "1", features = ["time"] }
toml = "0.9"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging"
] }
